FROM opensuse:harlequin
MAINTAINER Tomas Barton <barton.tomas@gmail.com>

RUN zypper addrepo http://download.opensuse.org/repositories/systemsmanagement:/puppet/openSUSE_13.2/ puppet | echo 'a'
RUN zypper install -y puppet && gem install deep_merge
