FROM centos:7
MAINTAINER Tomas Barton <barton.tomas@gmail.com>

RUN rpm -ivh http://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm
RUN yum -y install puppet sudo openssh-server openssh-clients curl ntpdate
